#!/bin/bash
#Check if the files exist:
if ! [[ -f $1 ]]
then 
echo "The first file doesn't exist." 1>&2
exit -4
fi
if ! [[ -r $1 ]]
then
echo "The first file is not readable." 1>&2
exit -8
fi
if ! [[ -f $2 ]]
then 
if ! [[ -w $2 ]]
then
echo "Can't create the file."
exit -4
fi
fi
if ! [[ -w $2 ]]
then
echo "The second file is not writable." 1>&2
exit -9
fi
#Write the reversed file:
exec 1>>$2
arr=()
readarray arr < $1
for ((index=${#arr[@]}; $index >=0; index--))
do
echo ${arr[$index]}|rev
done 
